---
- name: Adiciona chave do repositório
  rpm_key:
    key: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Adiciona repositório docker
  get_url:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644
